<?php

$buttonNames = array(
    'littlelink-custom' => 'LinkStack',
    'all-inkl' => 'ALL-INKL',
    'appstore' => 'App Store',
    'apple-books' => 'Apple Books',
    'apple-music' => 'Apple Music',
    'apple-podcasts' => 'Apple Podcasts',
    'bookwyrm' => 'BookWyrm',
    'dev-to' => 'DEV',
    'epic-games' => 'Epic Games',
    'f-droid' => 'F-Droid',
    'github' => 'GitHub',
    'gitlab' => 'GitLab',
    'itchio' => 'itch.io',
    'linkedin' => 'linkedIn',
    'linkstack' => 'LinkStack',
    'openstreetmap' => 'OpenStreetMap',
    'paypal' => 'PayPal',
    'picarto' => 'Picarto',
    'playstore' => 'Google Play',
    'soundcloud' => 'SoundCloud',
    'tiktok' => 'TikTok',
    'trakt' => 'Trakt',
    'vrchat' => 'VRChat',
    'whatsapp' => 'WhatsApp',
    'wordpress' => 'WordPress',
    'youtube' => 'YouTube',
    'youtube-music' => 'YouTube Music',
  );