@extends('layouts.sidebar')

@section('content')
    @if (file_exists(base_path('backups/updater-backups/')) && is_dir(base_path('backups/updater-backups/')))
            <?php
                    
                            if (isset($_GET['file'])) {
                                        $filename = $_GET['file'];
                                                
                                                            if (str_contains($filename, '/') || str_contains($filename, '\\') || !preg_match('/^[A-Za-z0-9._-]+$/', $filename)) {
                                                                            http_response_code(400);
                                                                                            exit('Invalid filename.');
                                                                                                        }
                                                                                                                
                                                                                                                            $baseDir = base_path('backups/updater-backups');
                                                                                                                                        $filepath = $baseDir . DIRECTORY_SEPARATOR . $filename;
                                                                                                                                                
                                                                                                                                                            $realBaseDir = realpath($baseDir);
                                                                                                                                                                        $realPath = realpath($filepath);
                                                                                                                                                                                
                                                                                                                                                                                            if ($realBaseDir === false || $realPath === false || !is_file($realPath)) {
                                                                                                                                                                                                            http_response_code(404);
                                                                                                                                                                                                                            exit('File not found.');
                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                            if (strpos($realPath, $realBaseDir . DIRECTORY_SEPARATOR) !== 0) {
                                                                                                                                                                                                                                                                            http_response_code(403);
                                                                                                                                                                                                                                                                                            exit('Access denied.');
                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                            while (ob_get_level()) {
                                                                                                                                                                                                                                                                                                                                            ob_end_clean();
                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                            header('Content-Type: application/octet-stream');
                                                                                                                                                                                                                                                                                                                                                                                        header('Content-Disposition: attachment; filename="' . basename($filename) . '"');
                                                                                                                                                                                                                                                                                                                                                                                                    header('Content-Length: ' . filesize($realPath));
                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                        readfile($realPath);
                                                                                                                                                                                                                                                                                                                                                                                                                                    exit();
                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                    ?>
                                                                                                                                                                                                                                                                                                                                                                                                                                                        @endif
                                                                                                                                                                                                                                                                                                                                                                                                                                                        @endsection
                                                                                                                                                                                                                                                                                                                                                                                                                                                        